[build]
  publish = "static"
  command = "echo 'Static files only - no server-side processing'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  python_runtime = "python3.9" 