[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PYTHONUNBUFFERED = "1"
RAILWAY = "true"

[service]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120" 